workspace(name = "notifbot")

android_sdk_repository(
    name = "androidsdk",
    api_level = 26,
)

git_repository(
    name = "org_pubref_rules_kotlin",
    remote = "https://github.com/pubref/rules_kotlin.git",
    commit = "069f25c065b0ba59645968a436d0a1031d6f2c41",
    sha256 = "10a902d8e5c23502e15aeef67fca51d0fda3f40d28855795a26dc0a1c371476b",
)
load("@org_pubref_rules_kotlin//kotlin:rules.bzl", "kotlin_repositories")
kotlin_repositories()

git_repository(
    name = "gmaven_rules",
    remote = "https://github.com/aj-michael/gmaven_rules",
    commit = "ccf6e13ba9357e6845179fe90e78b0fa24bd9f2b",
)
load("@gmaven_rules//:gmaven.bzl", "gmaven_rules")
gmaven_rules()

maven_jar(
    name = "com_squareup_okhttp3_okhttp",
    artifact = "com.squareup.okhttp3:okhttp:3.9.0",
    sha1 = "01b6c10b5120995a7542c1a31b7828fb8593c8ba",
)

maven_jar(
    name = "com_squareup_okio_okio",
    artifact = "com.squareup.okio:okio:1.13.0",
    sha1 = "a9283170b7305c8d92d25aff02a6ab7e45d06cbe",
)
